config/routes.rb
Rails.application.routes.draw do

  root to: "reports#feed"

  # Comments controller
  patch 'like/:comment_id', to: "comments#like", as: :like
  patch 'dislike/:comment_id', to: "comments#dislike", as: :dislike
  resources :comments

  # Sessions controller
	get 'login', to: "sessions#new", as: :login
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy", as: :logout

  # Users controller
  resources :users
  get 'users/:id', to: "users#show", as: :show_user

  # Reports controller
  resources :reports
  get 'feed', to: "reports#feed", as: :feed

  # Reset password controller
  get 'reset_password/search', to: "reset_password#search", as: :reset_password
  post 'reset_password/search', to: "reset_password#recover"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :report
  has_many :likes
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # PATCH like
  def like
      @comment = Comment.find_by(id: params[:comment_id])
      current_user.likes.build(comment_id: params[:comment_id]).save
      respond_to do |format|
        format.html { redirect_to feed_path }
        format.js
      end
    end

    # PATCH descurtir
    def dislike
      @comment = Comment.find_by(id: params[:comment_id])
      current_user.likes.find_by(comment_id: params[:comment_id]).destroy
      respond_to do |format|
        format.html { redirect_to feed_path }
        format.js
      end
    end


  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment,
                 notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        @report = @comment.report
        format.html { render "reports/show" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :report_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>

  <% if logged_in? %>
    <%= hidden_field_tag "comment[user_id]", current_user.id %>
    <% end %>

  <%= hidden_field_tag "comment[report_id]", params[:id] %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :comment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Report</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td>
          <% if logged_in? %>
            <%= comment.user.name %>
          <% else %>
            Anon
          <% end %>
        </td>
        <td><%= comment.report.title %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <% if logged_in? %>
    <%= @comment.user.name %>
  <% else %>
    Anon
  <% end %>
</p>


<p>
  <strong>Report:</strong>
  <%= @comment.report.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>