config/routes.rb
Rails.application.routes.draw do

  root to: "reports#feed"

  # Comments controller
  patch 'like/:comment_id', to: "comments#like", as: :like
  patch 'dislike/:comment_id', to: "comments#dislike", as: :dislike
  resources :comments

  # Sessions controller
	get 'login', to: "sessions#new", as: :login
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy", as: :logout

  # Users controller
  resources :users
  get 'users/:id', to: "users#show", as: :show_user

  # Reports controller
  resources :reports
  get 'feed', to: "reports#feed", as: :feed

  # Reset password controller
  get 'reset_password/search', to: "reset_password#search", as: :reset_password
  post 'reset_password/search', to: "reset_password#recover"
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments

  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { in: 2..100 }
  validates :content, presence: true
  validates :category, presence: true

  def last_update
  date = "#{updated_at.day}/#{updated_at.month}/#{updated_at.year}"
  time = "#{updated_at.hour}:#{updated_at.min}"
  "#{date} - #{time}"
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @comment = Comment.new
    @comments = @report.comments
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /feed
    def feed
      @report = Report.new
      @reports = Report.all.order(updated_at: :desc).paginate(:page => params[:page],
                  :per_page => 10)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :content, :image, :category_id, :user_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :report_title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :report_content %>
  </div>

  <div class="field">
    <%= form.label "Category" %>
    <%= select("report", "category_id", Category.all.collect {|category| [ category.name,
      category.id ] }, {include_blank: "Category"}, id: :category) %>
  </div>

    <%= hidden_field_tag "report[user_id]", current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/feed.html.erb
<h1>Newsfeed</h1>
<% @reports.each do |report| %>

  <h2> <%= link_to report.title, report_path(id: report.id)%> </h2>
  <% @report = report %>

  <p> By <%= link_to report.user.name, show_user_path(id: report.user.id) %> </p>
  <p> Last update: <%= report.last_update %> </p>
  <br>
  <% end %>

  <%= will_paginate @reports %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= report.content %></td>
        <td><%= report.category.name %></td>
        <td><%= report.user.name %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong><%= @report.title %></strong>
</h2>

<% if !@report.image.file.nil? %>
  <%= image_tag @report.image.thumb.url %>
<% end %>

<p>
  <%= @report.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @report.category.name %>
</p>

<p>
  <strong>By</strong>
  <%= @report.user.name %>
</p>

<p>
  <strong>Last updated at </strong>
  <%= @report.last_update %>
</p>

<p> <%= render "comments/form", comment: @comment %>
</p>

<h3> Comments: </h3>
  <% @comments.each do |comment| %>
    <p> <%= comment.content %> </p>
<% end %>

<% if logged_in? %>
  <%= link_to 'Edit', edit_report_path(@report) %>
  <% end %> |
<%= link_to 'Back', feed_path %>