config/routes.rb
Rails.application.routes.draw do

  root to: "reports#feed"

  # Comments controller
  patch 'like/:comment_id', to: "comments#like", as: :like
  patch 'dislike/:comment_id', to: "comments#dislike", as: :dislike
  resources :comments

  # Sessions controller
	get 'login', to: "sessions#new", as: :login
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy", as: :logout

  # Users controller
  resources :users
  get 'users/:id', to: "users#show", as: :show_user

  # Reports controller
  resources :reports
  get 'feed', to: "reports#feed", as: :feed

  # Reset password controller
  get 'reset_password/search', to: "reset_password#search", as: :reset_password
  post 'reset_password/search', to: "reset_password#recover"
end

app/views/layouts/_avisos.html.erb
<p><%= notice %></p>
<p><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "layouts/avisos" %>
    <%= link_to "Newsfeed", feed_path %>
    <% if logged_in? %>
    <% if current_user.admin %>
      <%= link_to "New report", new_report_path %>
      <% end %>
	  <p>
	    Hi <%= link_to current_user.name, show_user_path(id: current_user.id) %>!
      <%= link_to "Logout", logout_path, method: :delete %>

      </p>
	  <% else %>
      <p> <%= link_to "Login", login_path %> |
          <%= link_to "Join", new_user_path %></p>
    <% end %>
    <%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>